# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/new_nbdev2',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/new_nbdev2',
                'lib_path': 'new_nbdev2'},
  'syms': {'new_nbdev2.core': {'new_nbdev2.core.foo': ('core.html#foo', 'new_nbdev2/core.py')}}}